# Generated by Django 3.1.7 on 2021-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='A unique code that identifies the category', max_length=255, unique=True)),
                ('last_sync_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='A unique code that identifies the sub category', max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
                'ordering': ['-timestamp'],
                'abstract': False,
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
                'ordering': ['-timestamp'],
                'abstract': False,
                'unique_together': {('last_name', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_on', models.DateField(blank=True, default=None, null=True)),
                ('updated_on', models.DateField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('external_id', models.CharField(help_text='Article identifier in the external source', max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-updated_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSubCategory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.subcategory')),
            ],
            options={
                'verbose_name': 'article_subcategory',
                'verbose_name_plural': 'article_subcategories',
                'ordering': ['-timestamp'],
                'abstract': False,
                'unique_together': {('article', 'sub_category')},
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.author')),
            ],
            options={
                'verbose_name': 'article_author',
                'verbose_name_plural': 'article_authors',
                'ordering': ['-timestamp'],
                'abstract': False,
                'unique_together': {('article', 'author')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['updated_on'], name='articles_ar_updated_236d37_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_on'], name='articles_ar_created_be05dc_idx'),
        ),
    ]
